version: '3.8'

services:
  woof_database:
    image: postgres
    container_name: database_woof
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=woof
      - POSTGRES_PASSWORD=woof
      - POSTGRES_DB=woof
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: woof_app
    ports:
      - 3333:3000
    volumes:
      - .:/usr/app

# networks:
#   woofnet:
#     driver: bridge

volumes:
  pgdata:
    driver: local
